name: litespace-dev

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-litespace}
      POSTGRES_DB: litespace
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-dev@litespace.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "127.0.0.1:5050:80"
    networks:
      - postgres
    restart: unless-stopped
  redis:
    container_name: redis
    image: redis/redis-stack-server:latest
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    volumes:
      - redis:/data
    networks:
      - redis
  kafka:
    container_name: kafka
    image: apache/kafka-native
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      # Auto create topics on first use
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      # Configure listeners for both docker and host communication
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      # Listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      # Required for a single node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    container_name: kfaka-ui
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - "127.0.0.1:4006:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka
  docmost:
    container_name: docmost
    image: docmost/docmost:latest
    depends_on:
      - postgres
      - redis
    environment:
      APP_URL: "http://localhost:3006"
      APP_SECRET: "770i6T4e01tVprQyMb/FrCnIIhgmwRJS0WrGM0IWpAI="
      DATABASE_URL: "postgres://postgres:litespace@postgres:5432/docmost?schema=public"
      REDIS_URL: "redis://redis:6379"
      MAIL_DRIVER: "smtp"
      SMTP_HOST: "mail.litespace.org"
      SMTP_PORT: 465
      SMTP_USERNAME: dev
      SMTP_PASSWORD: ${DOCMOST_EMAIL_PASSOWRD}
      SMTP_SECURE: true
      MAIL_FROM_ADDRESS: dev@litespace.org
      MAIL_FROM_NAME: LiteSpace Dev
    ports:
      - "3006:3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage
    networks:
      - postgres
      - redis

networks:
  postgres:
    name: postgres
    driver: bridge
  redis:
    name: redis
    driver: bridge

volumes:
  postgres:
    name: litespace_postgres
  pgadmin:
    name: litespace_pgadmin
  docmost:
    name: litespace_docmost
  redis:
    name: litespace_redis
