export enum Route {
  Root = "/",
  Dashboard = "/dashboard",
  Schedule = "/schedule",
  EditSchedule = "/schedule/edit",
  Subscription = "/subscription",
  Settings = "/settings",
  Profile = "/profile",
  Payments = "/payments",
  Register = "/:role/register",
  Login = "/login",
  SelectUserType = "/select",
  SelectUserGender = "/gender",
  SetUserName = "/name",
  Tutors = "/tutors",
  Call = "/call/:id",
  TutorProfile = "/tutor/:id",
  TutorOnboarding = "/tutor/onboarding",
  Complete = "/complete",
  Lessons = "/lessons",
  Interviews = "/interviews",
}

export enum RoutePatterns {
  Register = "(/):role/register(/)",
  Login = "(/)login(/)",
  Call = "(/)call/:id(/)",
  Dashboard = "(/)dashboard(/)",
  Schedule = "(/)schedule(/)",
  Subscription = "(/)subscription(/)",
  Settings = "(/)settings(/)",
  Profile = "(/)profile(/)",
  Payments = "(/)payments(/)",
}
