export enum MutationKey {
  CreateInvoice = "create-invoice",
  CreateInterview = "create-interview",
  UpdateInterview = "update-interview",
  EditInvoice = "edit-invoice",
  CancelInvoice = "cancel-invoice",
  CancelLesson = "cancel-lesson",
  ShareFeedback = "share-feedback",
  ResetPassword = "reset-password",
  ForgetPassword = "forget-password",
  VerifyEmail = "verify-email",
  FlushCache = "flush-cache",
  CreateTopic = "create-topic",
  DeleteTopic = "delete-topic",
  UpdateTopic = "update-topic",
}
