export enum MutationKey {
  CreateInvoice = "create-invoice",
  CreateInterview = "create-interview",
  UpdateInterview = "update-interview",
  EditInvoice = "edit-invoice",
  CancelInvoice = "cancel-invoice",
  CancelLesson = "cancel-lesson",
  ShareFeedback = "share-feedback",
  ResetPassword = "reset-password",
  ForgetPassword = "forget-password",
  VerifyEmail = "verify-email",
  ReVerifyEmail = "reverify-email",
  FlushCache = "flush-cache",
  CreateTopic = "create-topic",
  DeleteTopic = "delete-topic",
  UpdateTopic = "update-topic",
  UpdateRoom = "update-room",
  BookLesson = "book-lesson",
  CreateRating = "create-rate",
  EditRating = "edit-rate",
  DeleteRating = "delete-rate",
  UpdateUser = "update-user",
}
