export enum QueryKey {
  FindTutorRating = "find-tutor-rating",
  FindTutors = "find-onboarded-tutors",
  FindTutorById = "find-tutor",
  FindTutorStats = "find-tutor-stats",
  FindTutorActivity = "find-tutor-acivity",
  FindTutorMeta = "find-tutor-meta",
  FindInvoicesByUser = "find-invoices-by-user",
  FindInvoiceStats = "find-invoice-stats",
  FindInvoices = "find-invoices",
  FindInterviewsPaged = "find-interviews-paged",
  FindInterviews = "find-interviews",
  FindInterviewer = "select-interviewer",
  FindInterviewSlots = "interviewer-slots",
  FindUserLesson = "find-user-lessons",
  FindLesson = "find-lessons",
  FindWithdrawalMethods = "find-withdrawal-methods",
  FindUserById = "find-user-by-id",
  FindStudentStats = "find-student-stats",
  FindTopic = "find-topic",
}
