import { ITutor } from "@litespace/types";
import { LocalId } from "@litespace/ui/locales";

export const TUTOR_DATA_ITEMS: (keyof ITutor.Full)[] = [
  "id",
  "email",
  "password",
  "name",
  "image",
  "address",
  "birthYear",
  "gender",
  "role",
  "verifiedEmail",
  "verifiedPhone",
  "verifiedWhatsApp",
  "creditScore",
  "city",
  "phone",
  "notificationMethod",
  "createdAt",
  "updatedAt",
  "about",
  "activated",
  "bio",
  "bypassOnboarding",
  "meta",
  "notice",
  "studioId",
  "thumbnail",
  "video",
];

export const TUTOR_DATA_ITEMS_MAP: Record<keyof ITutor.Full, LocalId> = {
  id: "tutor.items.id",
  email: "tutor.items.email",
  password: "tutor.items.password",
  name: "tutor.items.name",
  image: "tutor.items.image",
  address: "tutor.items.address",
  birthYear: "tutor.items.birthyear",
  gender: "tutor.items.gender",
  role: "tutor.items.role",
  verifiedEmail: "tutor.items.verified-email",
  verifiedPhone: "tutor.items.verified-phone",
  verifiedWhatsApp: "tutor.items.verified-whats",
  creditScore: "tutor.items.credit-score",
  city: "tutor.items.city",
  phone: "tutor.items.phone",
  notificationMethod: "tutor.items.notification-method",
  createdAt: "tutor.items.created-at",
  updatedAt: "tutor.items.updated-at",
  about: "tutor.items.about",
  activated: "tutor.items.activated",
  bio: "tutor.items.bio",
  bypassOnboarding: "tutor.items.bypass-onboarding",
  meta: "tutor.items.meta",
  notice: "tutor.items.notice",
  studioId: "tutor.items.studio-id",
  thumbnail: "tutor.items.thumbnail",
  video: "tutor.items.video",
};
