import { LocalId } from "@/locales";
import { ApiErrorCode, FieldError } from "@litespace/types";
export const apiErrorMap: Record<ApiErrorCode, LocalId> = {
  ["service-unavailable"]: "error.api.service-unavailable",
  ["unauthenticated"]: "error.api.unauthenticated",
  ["forbidden"]: "error.api.forbidden",
  ["bad-request"]: "error.api.bad-request",
  ["room-exists"]: "error.api.room-exists",
  ["user-exists"]: "error.api.user-exists",
  ["rating-exists"]: "error.api.rating-exists",
  ["subscription-exists"]: "error.api.subscription-exists",
  ["subscription-required"]: "error.api.subscription-required",
  ["no-enough-minutes"]: "error.api.no-enough-minutes",
  ["busy-tutor"]: "error.api.busy-tutor",
  ["busy-tutor-manager"]: "error.api.busy-tutor-manager",
  ["unexpected"]: "error.api.unexpected",
  ["not-found"]: "error.api.not-found",
  ["session-not-found"]: "error.api.session-not-found",
  ["user-not-found"]: "error.api.user-not-found",
  ["tutor-not-found"]: "error.api.tutor-not-found",
  ["transaction-not-found"]: "error.api.not-found",
  ["student-not-found"]: "error.api.student-not-found",
  ["lesson-not-found"]: "error.api.lesson-not-found",
  ["slot-not-found"]: "error.api.slot-not-found",
  ["rating-not-found"]: "error.api.rating-not-found",
  ["coupon-not-found"]: "error.api.coupon-not-found",
  ["asset-not-found"]: "error.api.asset-not-found",
  ["invite-not-found"]: "error.api.invite-not-found",
  ["invoice-not-found"]: "error.api.invoice-not-found",
  ["plan-not-found"]: "error.api.plan-not-found",
  ["room-not-found"]: "error.api.room-not-found",
  ["room-members-not-found"]: "error.api.room-members-not-found",
  ["report-not-found"]: "error.api.report-not-found",
  ["interview-not-found"]: "error.api.interview-not-found",
  ["topic-not-found"]: "error.api.topic-not-found",
  ["withdraw-method-not-found"]: "error.api.withdraw-method-not-found",
  ["subscription-not-found"]: "error.api.subscription-not-found",
  ["email-already-verified"]: "error.api.email-already-verified",
  ["illegal-invoice-update"]: "error.api.illegal-invoice-update",
  ["empty-request"]: "error.api.empty-request",
  ["user-already-verified"]: "error.api.user-already-verified",
  ["wrong-password"]: "error.api.wrong-password",
  ["conflicting-lessons"]: "error.api.conflicting-lessons",
  ["conflicting-interview"]: "error.api.conflicting-interview",
  ["conflicting-schedule"]: "error.api.conflicting-schedule",
  ["reached-booking-limit"]: "error.api.reached-booking-limit",
  ["phone-already-verified"]: "error.api.phone-already-verified",
  ["unresolved-phone"]: "error.api.unresolved-phone",
  ["incorrect-phone"]: "error.api.incorrect-phone",
  ["expired-verification-code"]: "error.api.expired-verification-code",
  ["invalid-verification-code"]: "error.api.invalid-verification-code",
  ["fawry-error"]: "error.api.fawry-error",
  ["large-file-size"]: "error.api.large-file-size",
  [FieldError.InvalidEmail]: "error.field.invalid-email",
  [FieldError.ShortPassword]: "error.field.short-password",
  [FieldError.LongPassword]: "error.field.long-password",
  [FieldError.InvalidPassword]: "error.field.invalid-password",
  [FieldError.InvalidUserName]: "error.field.invalid-user-name",
  [FieldError.ShortUserName]: "error.field.short-user-name",
  [FieldError.LongUserName]: "error.field.long-user-name",
  [FieldError.OldUser]: "error.field.old-user",
  [FieldError.YoungUser]: "error.field.young-user",
  [FieldError.EmptyBio]: "error.field.empty-bio",
  [FieldError.LongBio]: "error.field.long-bio",
  [FieldError.ShortBio]: "error.field.short-bio",
  [FieldError.InvalidBio]: "error.field.invalid-bio",
  [FieldError.ShortTutorAbout]: "error.field.short-tutor-about",
  [FieldError.LongTutorAbout]: "error.field.long-tutor-about",
  [FieldError.MaxNoticeExceeded]: "error.field.max-notice-exceeded",
  [FieldError.InvalidNotice]: "error.field.invalid-notice",
  [FieldError.InvalidInterviewFeedback]:
    "error.field.invalid-interview-feedback",
  [FieldError.TooShortInterviewFeedback]:
    "error.field.too-short-interview-feedback",
  [FieldError.TooLongInterviewFeedback]:
    "error.field.too-long-interview-feedback",
  [FieldError.InvalidInterviewNote]: "error.field.invalid-interview-note",
  [FieldError.TooShortInterviewNote]: "error.field.too-short-interview-note",
  [FieldError.TooLongInterviewNote]: "error.field.too-long-interview-note",
  [FieldError.TooLowInterviewLevel]: "error.field.too-low-interview-level",
  [FieldError.TooHighInterviewLevel]: "error.field.too-high-interview-level",
  [FieldError.TooLowRatingValue]: "error.field.too-low-rating-value",
  [FieldError.TooHighRatingValue]: "error.field.too-high-rating-value",
  [FieldError.TooLongRatingText]: "error.field.too-long-rating-text",
  [FieldError.TooShortRatingText]: "error.field.too-short-rating-text",
  [FieldError.PlanWeeklyMinutesOutOfRange]:
    "error.field.invalid-weekly-minutes",
  [FieldError.PlanDiscountOutOfRange]: "error.field.invalid-plan-discount",
  [FieldError.InvalidPlanPrice]: "error.field.invalid-plan-price",
  [FieldError.InvalidCouponCode]: "error.field.invalid-coupon-code",
  [FieldError.ZeroCouponDiscount]: "error.field.zero-coupon-discount",
  [FieldError.MaxCouponDiscountExceeded]:
    "error.field.max-coupon-discount-exceeded",
  [FieldError.InvalidCouponExpireDate]:
    "error.field.invalid-coupon-expire-date",
  [FieldError.ExpiredCouponExpireDate]:
    "error.field.expired-coupon-expire-date",
  [FieldError.InvalidMessageText]: "error.field.invalid-message-text",
  [FieldError.TooLongMessageText]: "error.field.too-long-message-text",
  [FieldError.TooShortMessageText]: "error.field.too-short-message-text",
  [FieldError.WithdrawMinAmountAboveMaxAmount]:
    "error.field.withdraw-min-amount-above-max-amount",
  [FieldError.WithdrawMaxAmountZeroOrNegative]:
    "error.field.withdraw-max-amount-zero-or-negative",
  [FieldError.WithdrawMinAmountZeroOrNegative]:
    "error.field.withdraw-min-amount-zero-or-negative",
  [FieldError.ZeroInvoiceAmount]: "error.field.zero-invoice-amount",
  [FieldError.InvoiceMinAmountSubceeded]:
    "error.field.invoice-min-amount-subceeded",
  [FieldError.InvoiceMaxAmountExceeded]:
    "error.field.invoice-max-amount-exceeded",
  [FieldError.EmptyInvoiceNote]: "error.field.empty-invoice-note",
  [FieldError.InvalidInvoiceNote]: "error.field.invalid-invoice-note",
  [FieldError.TooLongInvoiceNote]: "error.field.too-long-invoice-note",
  [FieldError.InvalidPhone]: "error.field.invalid-phone-number",
  [FieldError.InvalidInstapayIPA]: "error.field.invalid-instapay-ipa",
  [FieldError.EmptyBankName]: "error.field.empty-bank-name",
  [FieldError.InvalidBankName]: "error.field.invalid-bank-name",
  [FieldError.InvalidBankAccountNumber]: "error.field.invalid-bank-number",
  [FieldError.InvalidWithdrawMethod]: "error.field.invalid-withdraw-method",
  [FieldError.ShortTopicName]: "error.field.short-topic-name",
  [FieldError.LongTopicName]: "error.field.long-topic-name",
  [FieldError.InvalidType]: "error.field.invalid-type",
  [FieldError.ShortContactRequestTitle]:
    "error.field.short-contact-request-title",
  [FieldError.LongContactRequestTitle]:
    "error.field.long-contact-request-title",
  [FieldError.ShortContactRequestMessage]:
    "error.field.short-contact-request-message",
  [FieldError.LongContactRequestMessage]:
    "error.field.long-contact-request-message",
};
