import plugin from "tailwindcss/plugin";
import { resolve } from "node:path";

export const path = resolve(__dirname);

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        cairo: ["Cairo", "sans-serif"],
      },
      width: {
        "spinner-x": "1.5rem",
        "spinner-2x": "2rem",
        "spinner-3x": "2.5rem",
        "spinner-4x": "4rem",
        "spinner-5x": "5rem",
      },
      height: {
        "spinner-x": "1.5rem",
        "spinner-2x": "2rem",
        "spinner-3x": "2.5rem",
        "spinner-4x": "4rem",
        "spinner-5x": "5rem",
      },
      aspectRatio: {
        desktop: "16 / 9",
        mobile: "9 / 16",
      },
      fontSize: {
        h1: "4rem",
        h2: "3rem",
        h3: "2.5rem",
        h4: "2rem",
        "subtitle-1": "1.5rem",
        "subtitle-2": "1.25rem",
        body: "1rem",
        caption: "0.875rem",
        tiny: "0.75rem",
        "extra-tiny": "0.625rem",
      },
      blur: {
        ellipse: "100px",
      },
      maxHeight: {
        "chat-desktop": "calc(100vh - 106px)",
        "chat-tablet": "calc(100vh - 88px)",
        "chat-mobile": "calc(100vh - 72px)",
      },
      zIndex: {
        "select-item": "1",
        "radio-button": "1",
        "chat-avatar": "1",
        "calendar-hour": "1",
        "landing-ellipse": "1",
        "iframe-dialog-overlay": "1",
        "onboarding-flow-step-order": "1",
        navbar: "1",
        "stream-v2-avatar": "1",
        "stream-v2-mute-icon": "2",
        "stream-v2-speaking": "2",
        "stream-v2-user-name": "2",
        "stream-v2-spinner": "2",
        "landing-sidebar": "2",
        "iframe-dialog-conent": "2",
        sidebar: "2",
        "free-badge": "2",
        "online-indicator": "2",
        "recommended-badge": "3",
        "session-movable-stream": "3",
        "floating-buttons": "9",
        quote: "10",
        "dialog-overlay": "10",
        "mobile-sidebar": "10",
        dialog: "11",
        "confirm-dialog-overlay": "12",
        "confirm-dialog-content": "13",
        "select-dropdown": "14",
        tooltip: "15",
        toast: "16",
        "stream-avatar": "16",
        "stream-chat": "10",
        "stream-chat-options": "19",
        "video-player-settings-menu": "20",
      },
      screens: {
        "2xs": "400px",
        xs: "480px",
        "3xl": "1600px",
      },
      containers: {
        "2md": "30rem",
      },
      backgroundImage: {
        "toast-success":
          "radial-gradient(50% 50% at 50% 50%, rgba(0, 237, 81, 0.12) 0%, rgba(0, 237, 123, 0) 100%)",
        "toast-warning":
          "radial-gradient(50% 50% at 50% 50%, rgba(255, 212, 38, 0.11) 0%, rgba(255, 212, 38, 0) 100%)",
        "toast-error":
          "radial-gradient(50% 50% at 50% 50%, rgba(240, 66, 72, 0.13) 0%, rgba(240, 66, 72, 0) 100%)",
        loader:
          "conic-gradient(from 180deg at 50% 50%, #1D7C4E 0deg, rgba(17,173,207,0) 360deg)",
        telegram: "linear-gradient(180deg, #2AABEE 0%, #229ED9 100%)",
        whatsapp: "linear-gradient(248.7deg, #61FD7D -70.28%, #25CF43 96.43%)",
      },
      colors: {
        avatar: {
          green: {
            1: "var(--avatar-green-1)",
            2: "var(--avatar-green-2)",
            3: "var(--avatar-green-3)",
            4: "var(--avatar-green-4)",
          },
          blue: {
            1: "var(--avatar-blue-1)",
            2: "var(--avatar-blue-2)",
            3: "var(--avatar-blue-3)",
            4: "var(--avatar-blue-4)",
          },
          pink: {
            1: "var(--avatar-pink-1)",
            2: "var(--avatar-pink-2)",
            3: "var(--avatar-pink-3)",
            4: "var(--avatar-pink-4)",
          },
          redish: {
            1: "var(--avatar-redish-1)",
            2: "var(--avatar-redish-2)",
            3: "var(--avatar-redish-3)",
            4: "var(--avatar-redish-4)",
          },
          violate: {
            1: "var(--avatar-violate-1)",
            2: "var(--avatar-violate-2)",
            3: "var(--avatar-violate-3)",
            4: "var(--avatar-violate-4)",
          },
        },
        dash: {
          sidebar: "hsl(var(--background-dash-sidebar))",
          canva: "hsl(var(--background-dash-canvas))",
        },
        red: {
          100: "var(--colors-red1)",
          200: "var(--colors-red2)",
          300: "var(--colors-red3)",
          400: "var(--colors-red4)",
          500: "var(--colors-red5)",
          600: "var(--colors-red6)",
          700: "var(--colors-red7)",
          800: "var(--colors-red8)",
          900: "var(--colors-red9)",
        },
        amber: {
          100: "var(--colors-amber1)",
          200: "var(--colors-amber2)",
          300: "var(--colors-amber3)",
          400: "var(--colors-amber4)",
          500: "var(--colors-amber5)",
          600: "var(--colors-amber6)",
          700: "var(--colors-amber7)",
          800: "var(--colors-amber8)",
          900: "var(--colors-amber9)",
          1000: "var(--colors-amber10)",
          1100: "var(--colors-amber11)",
          1200: "var(--colors-amber12)",
        },
        blue: {
          100: "var(--colors-blue1)",
          200: "var(--colors-blue2)",
          300: "var(--colors-blue3)",
          400: "var(--colors-blue4)",
          500: "var(--colors-blue5)",
          600: "var(--colors-blue6)",
          700: "var(--colors-blue7)",
          800: "var(--colors-blue8)",
          900: "var(--colors-blue9)",
          1000: "var(--colors-blue10)",
          1100: "var(--colors-blue11)",
          1200: "var(--colors-blue12)",
        },
        control: "hsl(var(--border-control))",
        muted: "hsl(var(--background-muted))",
        foreground: {
          DEFAULT: "hsl(var(--foreground-default))",
          muted: "hsl(var(--foreground-muted))",
          semi: "hsl(var(--foreground-semi-light))",
          light: "hsl(var(--foreground-light))",
          lighter: "hsl(var(--foreground-lighter))",
        },
        success: {
          50: "var(--success-50)",
          100: "var(--success-100)",
          200: "var(--success-200)",
          300: "var(--success-300)",
          400: "var(--success-400)",
          500: "var(--success-500)",
          600: "var(--success-600)",
          700: "var(--success-700)",
          800: "var(--success-800)",
          900: "var(--success-900)",
          950: "var(--success-950)",
        },
        warning: {
          DEFAULT: "var(--warning-default)",
          50: "var(--warning-50)",
          100: "var(--warning-100)",
          200: "var(--warning-200)",
          300: "var(--warning-300)",
          400: "var(--warning-400)",
          500: "var(--warning-500)",
          600: "var(--warning-600)",
          700: "var(--warning-700)",
          800: "var(--warning-800)",
          900: "var(--warning-900)",
          950: "var(--warning-950)",
        },
        destructive: {
          DEFAULT: "var(--destructive-default)",
          50: "var(--destructive-50)",
          100: "var(--destructive-100)",
          200: "var(--destructive-200)",
          300: "var(--destructive-300)",
          400: "var(--destructive-400)",
          500: "var(--destructive-500)",
          600: "var(--destructive-600)",
          700: "var(--destructive-700)",
          800: "var(--destructive-800)",
          900: "var(--destructive-900)",
          950: "var(--destructive-950)",
        },
        border: {
          DEFAULT: "hsl(var(--border-default))",
          stronger: "hsl(var(--border-stronger))",
          strong: "hsl(var(--border-strong))",
          alternative: "hsl(var(--border-alternative))",
          control: "hsl(var(--border-control))",
          secondary: "hsl(var(--border-secondary))",
          muted: "hsl(var(--border-muted))",
          overlay: "hsl(var(--border-overlay))",
          avatar: "rgba(0, 0, 0, 0.4)",
          button: {
            DEFAULT: "hsl(var(--border-button-default))",
            hover: "hsl(var(--border-button-hover))",
          },
        },
        overlay: {
          DEFAULT: "hsl(var(--background-overlay-default))",
          dialog: "var(--colors-overlay-dialog)",
        },
        background: {
          DEFAULT: "hsl(var(--background-default))",
          200: "hsl(var(--background-200))",
          control: "hsl(var(--background-control))",
          selection: "hsl(var(--background-selection))",
          video: "hsla(228, 53%, 21%, 0.8)",
          indicator: "rgba(0, 0, 0, 0.3)",
          internet: "rgba(51, 38, 0, 0.6)",
          speaking: "rgba(27, 84, 164, 0.8)",
          "loader-spinner": "rgba(29,124,78,1)",
          dialog: {
            DEFAULT: "hsl(var(--background-dialog-default))",
          },
          button: {
            DEFAULT: "hsl(var(--background-button-default))",
            play: "rgba(255, 255, 255, 0.25)",
          },
          alternative: {
            DEFAULT: "hsl(var(--background-alternative-default))",
            200: "hsl(var(--background-alternative-200))",
          },
        },
        surface: {
          75: "hsl(var(--background-surface-75))",
          100: "hsl(var(--background-surface-100))",
          200: "hsl(var(--background-surface-200))",
          300: "hsl(var(--background-surface-300))",
          400: "hsl(var(--background-surface-400))",
        },
        brand: {
          DEFAULT: "var(--brand-default)",
          link: "hsl(var(--brand-link))",
          button: "hsl(var(--brand-button))",
          50: "var(--brand-50)",
          100: "var(--brand-100)",
          200: "var(--brand-200)",
          300: "var(--brand-300)",
          400: "var(--brand-400)",
          500: "var(--brand-500)",
          600: "var(--brand-600)",
          700: "var(--brand-700)",
          800: "var(--brand-800)",
          900: "var(--brand-900)",
        },
        secondary: {
          DEFAULT: "var(--secondary-default)",
          50: "var(--secondary-50)",
          100: "var(--secondary-100)",
          200: "var(--secondary-200)",
          300: "var(--secondary-300)",
          400: "var(--secondary-400)",
          500: "var(--secondary-500)",
          600: "var(--secondary-600)",
          700: "var(--secondary-700)",
          800: "var(--secondary-800)",
          900: "var(--secondary-900)",
          950: "var(--secondary-950)",
        },
        natural: {
          DEFAULT: "var(--natural-default)",
          0: "var(--natural-0)",
          50: "var(--natural-50)",
          100: "var(--natural-100)",
          200: "var(--natural-200)",
          300: "var(--natural-300)",
          400: "var(--natural-400)",
          500: "var(--natural-500)",
          600: "var(--natural-600)",
          700: "var(--natural-700)",
          800: "var(--natural-800)",
          900: "var(--natural-900)",
          950: "var(--natural-950)",
        },
        "calendar-day-level": {
          1: "var(--color-calendar-graph-day-L1-bg)",
          2: "var(--color-calendar-graph-day-L2-bg)",
          3: "var(--color-calendar-graph-day-L3-bg)",
          4: "var(--color-calendar-graph-day-L4-bg)",
        },
        "calendar-day-border-level": {
          1: "var(--color-calendar-graph-day-L1-border)",
          2: "var(--color-calendar-graph-day-L2-border)",
          3: "var(--color-calendar-graph-day-L3-border)",
          4: "var(--color-calendar-graph-day-L4-border)",
        },
        "discount-default": "#0A291A1A",
        "discount-primary": "#FFFFFFCC",
      },
      keyframes: {
        "slide-in": {
          from: { transform: "translateX(-25px)" },
          to: { transform: "translateX(0)" },
        },
      },
      rotate: {
        "x-180": "180deg",
      },
      animation: {
        "slide-in": "slide-in 150ms cubic-bezier(0.16, 1, 0.3, 1)",
      },
      lineClamp: {
        3: "3",
        4: "4",
        5: "5",
      },
      borderColor: {
        "button-main-default": "var(--border-button-main-primary-default)",
        "button-main-active": "var(--border-button-main-primary-active)",
        "button-natural-default":
          "var(--border-button-natural-primary-default)",
        "button-natural-active": "var(--border-button-natural-primary-active)",
      },
    },
    boxShadow: {
      "ls-x-small": "0px 6px 20px 0px rgba(0, 0, 0, 0.08)",
      "ls-small": "0px 6px 20px 0px rgba(0, 0, 0, 0.1)",
      "ls-medium": "0px 6px 20px 0px rgba(0, 0, 0, 0.15)",
      "ls-large": "0px 6px 20px 0px rgba(0, 0, 0, 0.2)",
      "ls-x-large": "0px 6px 20px 0px rgba(0, 0, 0, 0.25)",
      "message-panel": "0px 4px 25px 0px #0000000D",
      "plan-info": "0px 4px 25px 0px rgba(0, 0, 0, 0.04)",
      sidebar: "0px 14px 42px 0px rgba(0, 0, 0, 0.08)",
      "app-sidebar": "0px 14px 42px 0px rgba(0, 0, 0, 0.08)",
      "app-navbar": "0px 4px 20px 0px rgba(0, 0, 0, 0.08)",
      "app-navbar-mobile": "0px 4px 20px 0px rgba(0, 0, 0, 0.1)",
      "input-focus": "0px 0px 10px 4px rgba(43, 181, 114, 0.25)",
      "input-error": "0px 1px 10px 4px rgba(204, 0, 0, 0.25)",
      "switch-thumb": "0px 2px 4px 0px rgba(39, 39, 39, 0.1)",
      "switch-root": "0px 4px 20px 0px rgba(43, 181, 114, 0.2)",
      "page-content": "0px 4px 20px 0px rgba(0, 0, 0, 0.1)",
      calendar: "0px 4px 20px 0px rgba(0, 0, 0, 0.08)",
      "dialog-confirm": "0px 4px 20px 0px rgba(0, 0, 0, 0.15)",
      "lesson-event-card": "0px 4px 20px 0px rgba(0, 0, 0, 0.15)",
      toast:
        "0px 16px 24px 0px rgba(0, 0, 0, 0.10), 0px 6px 30px 0px rgba(0, 0, 0, 0.10), 0px 8px 10px 0px rgba(0, 0, 0, 0.15)",
      "unread-count": "0px 4px 15px 0px rgba(29, 124, 78, 0.2)",
      "unread-count-dark": "0px 4px 15px 0px rgba(29, 124, 78, 0.2)",
      "chat-date": "0px 4px 15px 0px rgba(0, 0, 0, 0.15)",
      "chat-header": "0px 4px 20px 0px rgba(0, 0, 0, 0.08)",
      tooltip: "0px 4px 20px 0px rgba(0, 0, 0, 0.15)",
      "plan-tooltip": "0px 4px 20px 0px rgba(0, 0, 0, 0.08)",
      "feedback-card": "0px 4px 20px 0px rgba(0, 0, 0, 0.15)",
      "dark-feedback-card": "0px 4px 15px 0px rgba(255, 255, 255, 0.08)",
      "pre-call": "0px 4px 20px 0px rgba(0, 0, 0, 0.1)",
      "date-selection-item": "0px 4px 15px 0px rgba(0, 0, 0, 0.15)",
      "time-selection-item": "0px 4px 15px 0px #00000008",
      "exclaimation-mark-video": "0px 4px 20px 1px rgba(204, 0, 0, 0.25)",
      "tutor-profile": "0px 4px 20px 0px rgba(0, 0, 0, 0.08)",
      "student-profile": "0px 4px 20px 0px rgba(0, 0, 0, 0.08)",
      "plan-card": "0px 4px 20px 0px rgba(0, 0, 0, 0.2)",
      "plan-card-label": "0px 4px 20px 0px rgba(0, 0, 0, 0.15)",
      "alert-circle": "0px 4px 15px 0px rgba(0, 0, 0, 0.1)",
      header: "0px 4px 20px 0px rgba(0, 0, 0, .1)",
      "select-menu": "0px 4px 20px 0px rgba(0, 0, 0, 0.1)",
      "form-submit-container": "0px -4px 20px 0px rgba(0, 0, 0, .08)",
      "tutor-card": "0px 4px 20px 0px rgba(0, 0, 0, 0.1)",
      slot: "0px 4px 20px 0px rgba(0, 0, 0, .1)",
      "session-movable-stream": "0px 4px 20px 0px rgba(0, 0, 0, 0.10)",
      "plan-card-v2": "0px 4px 20px 0px rgba(0, 0, 0, .03)",
      "time-selection": "0px 4px 15px 0px #00000008",
      "mobile-sidebar": "0px -4px 25px 0px rgba(0, 0, 0, 0.08)",
      "sidebar-more-menu": "0px 4px 20px 0px rgba(0, 0, 0, .15)",
    },
  },
  plugins: [
    require("tailwind-scrollbar"),
    require("@tailwindcss/container-queries"),
    plugin(({ addVariant }) => {
      addVariant("webkit-slider-thumb", "&::-webkit-slider-thumb");
      addVariant("moz-slider-thumb", "&::-moz-range-thumb");
    }),
  ],
};
