export enum Route {
  Call = "/call/:id/:type",
  Chat = "/chat",
  Complete = "/complete",
  Dashboard = "/dashboard",
  EditSchedule = "/schedule/edit",
  Interviews = "/interviews",
  Invoices = "/invoices",
  Login = "/login",
  Payments = "/payments",
  Profile = "/profile",
  Register = "/:role/register",
  ResetPassword = "/reset-password",
  Root = "/",
  Schedule = "/schedule",
  SelectUserType = "/select",
  SelectUserGender = "/gender",
  SetUserName = "/name",
  TutorSettings = "/t/settings",
  StudentSettings = "/s/settings",
  Subscription = "/subscription",
  TutorOnboarding = "/tutor/onboarding",
  Tutors = "/tutors",
  TutorProfile = "/:id/tutor",
  UpcomingLessons = "/upcoming-lessons",
  VerifyEmail = "/verify-email",
  Lesson = "/lesson/:id",
}

export enum RoutePatterns {
  Register = "(/):role/register(/)",
  Login = "(/)login(/)",
  Call = "(/)call/:id(/)",
  Dashboard = "(/)dashboard(/)",
  Schedule = "(/)schedule(/)",
  Subscription = "(/)subscription(/)",
  Settings = "(/)settings(/)",
  Profile = "(/)profile(/)",
  Payments = "(/)payments(/)",
  ResetPassword = "(/)reset-password(/)",
  VerifyEmail = "(/)verify-email(/)",
}
