name: Checks

env:
  DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
  CLICKUP_API_TOKEN: ${{ secrets.CLICKUP_API_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}

on:
  pull_request:

  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.1"
      - name: Enable pnpm
        run: corepack enable pnpm
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Lint all workspaces
        run: pnpm lint
      - name: Check formatting
        run: pnpm prettier:check
      - name: Analyze intl messages
        run: pnpm intl inspect --fail
      - name: Build packages
        run: pnpm build:pkgs
      - name: Check typescript errors
        run: pnpm check:all
      - name: Pull request audit using dangerjs
        run: pnpm danger ci --dangerfile scripts/dangerfile.ts
      - name: Create ClickUp tasks for reviewers
        run: pnpm clickup pr-review-tasks -t "${{ github.event.pull_request.title }}" -d "${{ github.event.pull_request.body }}" -n ${{ github.event.number }}
