name: Staging deployment
env:
  DEPLOYER_STAGING_SECRET: ${{ secrets.DEPLOYER_STAGING_SECRET }}
on:
  pull_request:
    branches:
      - "master"
    types: [closed]
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Trigger staging deployment using the deployer server
        run: curl --fail -X POST "https://deployer.staging.litespace.org?workspaces=all&secret=$DEPLOYER_STAGING_SECRET"
