name: Staging deployment
env:
  APOLLO_STAGING_SECRET: ${{ secrets.APOLLO_STAGING_SECRET }}
on:
  pull_request:
    branches:
      - "master"
    types: [closed]
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Trigger staging deployment using the Apollo server
        run: curl --fail -X POST "https://apollo.staging.litespace.org?workspaces=all&secret=$APOLLO_STAGING_SECRET"
