name: Deploy

on:
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.1"
      - name: Enable Yarn
        run: corepack enable
      - name: Install dependencies
        run: yarn
      - name: Build types
        run: yarn build:types
      - name: Build Atlas SDK
        run: yarn build:atlas
      - name: Build Uilib
        run: yarn build:uilib
      # Oribit Deployment
      - name: Pull Orbit from Vercel
        run: yarn vercel:ci pull "orbit" "./orbit/" --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Orbit using Vercel
        run: yarn build:orbit:vercel
      - name: Deploy Orbit to Vercel
        run: yarn deploy:orbit:vercel --token=${{ secrets.VERCEL_TOKEN }}
      # Nova Deployment
      - name: Pull Nova from Vercel
        run: yarn vercel:ci pull "nova" "./web/" --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Nova using Vercel
        run: yarn build:nova:vercel
      - name: Deploy Nova to Vercel
        run: yarn deploy:nova:vercel --token=${{ secrets.VERCEL_TOKEN }}
